name: LZ Management Groups Deployment
on:
  workflow_dispatch:
    inputs:
      jobToRun:
        description: 'Select Job'
        required: true
        default: 'Bootstrap'
        type: choice
        options:
          - Bootstrap
          - Create Management Groups
          - Destroy Management Groups
          - DeployHubSpoke
          - DestroyHubSpoke
env:
  terraformVersion: '1.8.0'

permissions:
  id-token: write
  contents: read

jobs:
  Bootstrap:
    if: ${{ github.event.inputs.jobToRun == 'Bootstrap' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
     
      - name: Run bootstrap script for creating storage for statefile    
        run: |
          chmod +x modules/managementgroups/bootstrap.sh
          modules/managementgroups/bootstrap.sh
